### ISSUE TITLE
Requirements not met

### ISSUE THREAD

**Issue by de-sh** [HTTP-APIs/hydra-openapi-parser#10]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

The tests fail as the requirement of YAML is not satisfied.

### Expected Behaviour:

YAML dependency is mentioned in requirements.txt

### Steps to reproduce:

Clone repo and run `python -m unittest discover

### Do you want to work on this issue?
yes

**Comment by Mec-iS** [comment]
e80f75f
